"""new pricing updates

Revision ID: 00dd38967487
Revises: bd0f3614a367
Create Date: 2020-06-20 23:57:02.601143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00dd38967487'
down_revision = 'bd0f3614a367'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teamprice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('team', sa.String(length=140), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teamprice_date'), 'teamprice', ['date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_teamprice_date'), table_name='teamprice')
    op.drop_table('teamprice')
    # ### end Alembic commands ###
