"""social auth

Revision ID: 0cefe1afad96
Revises: 25bf0a30e1c7
Create Date: 2020-04-08 21:18:40.788408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cefe1afad96'
down_revision = '25bf0a30e1c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('social_auth_partial',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('token', sa.VARCHAR(length=32), nullable=True),
    sa.Column('data', sa.TEXT(), nullable=True),
    sa.Column('next_step', sa.INTEGER(), nullable=True),
    sa.Column('backend', sa.VARCHAR(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_social_auth_partial_token', 'social_auth_partial', ['token'], unique=False)
    op.create_table('social_auth_code',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(length=200), nullable=True),
    sa.Column('code', sa.VARCHAR(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', 'email')
    )
    op.create_index('ix_social_auth_code_code', 'social_auth_code', ['code'], unique=False)
    op.create_table('social_auth_usersocialauth',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('provider', sa.VARCHAR(length=32), nullable=True),
    sa.Column('extra_data', sa.TEXT(), nullable=True),
    sa.Column('uid', sa.VARCHAR(length=255), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_social_auth_usersocialauth_user_id', 'social_auth_usersocialauth', ['user_id'], unique=False)
    op.create_table('social_auth_association',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('server_url', sa.VARCHAR(length=255), nullable=True),
    sa.Column('handle', sa.VARCHAR(length=255), nullable=True),
    sa.Column('secret', sa.VARCHAR(length=255), nullable=True),
    sa.Column('issued', sa.INTEGER(), nullable=True),
    sa.Column('lifetime', sa.INTEGER(), nullable=True),
    sa.Column('assoc_type', sa.VARCHAR(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('server_url', 'handle')
    )
    op.create_table('social_auth_nonce',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('server_url', sa.VARCHAR(length=255), nullable=True),
    sa.Column('timestamp', sa.INTEGER(), nullable=True),
    sa.Column('salt', sa.VARCHAR(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('server_url', 'timestamp', 'salt')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('social_auth_nonce')
    op.drop_table('social_auth_association')
    op.drop_index('ix_social_auth_usersocialauth_user_id', table_name='social_auth_usersocialauth')
    op.drop_table('social_auth_usersocialauth')
    op.drop_index('ix_social_auth_code_code', table_name='social_auth_code')
    op.drop_table('social_auth_code')
    op.drop_index('ix_social_auth_partial_token', table_name='social_auth_partial')
    op.drop_table('social_auth_partial')
    # ### end Alembic commands ###
