"""price

Revision ID: 1869899c7176
Revises: 036b44e65133
Create Date: 2020-05-25 14:22:49.557969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1869899c7176'
down_revision = '036b44e65133'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team', sa.Column('price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team', 'price')
    # ### end Alembic commands ###
