"""auto buy price

Revision ID: 88c5acb22fdb
Revises: 9a852767a000
Create Date: 2020-06-11 01:03:38.424209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88c5acb22fdb'
down_revision = '9a852767a000'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team', sa.Column('buy_at', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team', 'buy_at')
    # ### end Alembic commands ###
