"""total assets

Revision ID: c373e9aa16b0
Revises: 7905bb5c53f3
Create Date: 2020-05-27 11:05:35.971307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c373e9aa16b0'
down_revision = '7905bb5c53f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('total_assets', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'total_assets')
    # ### end Alembic commands ###
